//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBAllphaModel : DbContext
    {
        public DBAllphaModel()
            : base("name=DBAllphaModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CompraT> CompraT { get; set; }
        public DbSet<LogsT> LogsT { get; set; }
        public DbSet<TbAlbum> TbAlbum { get; set; }
        public DbSet<TbUser> TbUser { get; set; }
        public DbSet<TrackT> TrackT { get; set; }
    }
}
